#!/bin/sh
chown -R root:root /
chmod 700 /root
chown -R ctf:ctf /home/ctf

# 挂载文件系统
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs tmpfs /tmp
mount -t devtmpfs devtmpfs /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts
mount -t debugfs none /sys/kernel/debug

# start
echo -e "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n"

# 设置权限
chmod u+s /bin/su
cd /
insmod /tuc.ko

# 分配新的 TTY (指定 ttyS0)
exec </dev/ttyS0 >/dev/ttyS0 2>&1
# su ctf -c sh
su root -c sh

poweroff -d 0  -f
