/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pack2.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pack2.pb-c.h"
void   pack2__pack2_msg__pack2_msg_msg__init
                     (Pack2__Pack2Msg__Pack2MsgMsg         *message)
{
  static const Pack2__Pack2Msg__Pack2MsgMsg init_value = PACK2__PACK2_MSG__PACK2_MSG_MSG__INIT;
  *message = init_value;
}
void   pack2__pack2_msg__init
                     (Pack2__Pack2Msg         *message)
{
  static const Pack2__Pack2Msg init_value = PACK2__PACK2_MSG__INIT;
  *message = init_value;
}
size_t pack2__pack2_msg__get_packed_size
                     (const Pack2__Pack2Msg *message)
{
  assert(message->base.descriptor == &pack2__pack2_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pack2__pack2_msg__pack
                     (const Pack2__Pack2Msg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pack2__pack2_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pack2__pack2_msg__pack_to_buffer
                     (const Pack2__Pack2Msg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pack2__pack2_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pack2__Pack2Msg *
       pack2__pack2_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pack2__Pack2Msg *)
     protobuf_c_message_unpack (&pack2__pack2_msg__descriptor,
                                allocator, len, data);
}
void   pack2__pack2_msg__free_unpacked
                     (Pack2__Pack2Msg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pack2__pack2_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue pack2__pack2_msg__pack2_msg_msg__pack2_msg_msg_enum__enum_values_by_number[2] =
{
  { "pack2_msg_msg_enum_value1", "PACK2__PACK2_MSG__PACK2_MSG_MSG__PACK2_MSG_MSG_ENUM__pack2_msg_msg_enum_value1", 0 },
  { "pack2_msg_msg_enum_value2", "PACK2__PACK2_MSG__PACK2_MSG_MSG__PACK2_MSG_MSG_ENUM__pack2_msg_msg_enum_value2", 3 },
};
static const ProtobufCIntRange pack2__pack2_msg__pack2_msg_msg__pack2_msg_msg_enum__value_ranges[] = {
{0, 0},{3, 1},{0, 2}
};
static const ProtobufCEnumValueIndex pack2__pack2_msg__pack2_msg_msg__pack2_msg_msg_enum__enum_values_by_name[2] =
{
  { "pack2_msg_msg_enum_value1", 0 },
  { "pack2_msg_msg_enum_value2", 1 },
};
const ProtobufCEnumDescriptor pack2__pack2_msg__pack2_msg_msg__pack2_msg_msg_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "pack2.pack2_msg.pack2_msg_msg.pack2_msg_msg_enum",
  "pack2_msg_msg_enum",
  "Pack2__Pack2Msg__Pack2MsgMsg__Pack2MsgMsgEnum",
  "pack2",
  2,
  pack2__pack2_msg__pack2_msg_msg__pack2_msg_msg_enum__enum_values_by_number,
  2,
  pack2__pack2_msg__pack2_msg_msg__pack2_msg_msg_enum__enum_values_by_name,
  2,
  pack2__pack2_msg__pack2_msg_msg__pack2_msg_msg_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor pack2__pack2_msg__pack2_msg_msg__field_descriptors[3] =
{
  {
    "pack2_msg_msg_value1",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Pack2__Pack2Msg__Pack2MsgMsg, pack2_msg_msg_value1),
    &pack2__pack2_msg__pack2_msg_enum1__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pack2_msg_msg_value2",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Pack2__Pack2Msg__Pack2MsgMsg, pack2_msg_msg_value2),
    &pack2__pack2_msg__pack2_msg_enum2__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pack2_msg_msg_value3",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Pack2__Pack2Msg__Pack2MsgMsg, pack2_msg_msg_value3),
    &pack2__pack2_msg__pack2_msg_msg__pack2_msg_msg_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pack2__pack2_msg__pack2_msg_msg__field_indices_by_name[] = {
  0,   /* field[0] = pack2_msg_msg_value1 */
  1,   /* field[1] = pack2_msg_msg_value2 */
  2,   /* field[2] = pack2_msg_msg_value3 */
};
static const ProtobufCIntRange pack2__pack2_msg__pack2_msg_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pack2__pack2_msg__pack2_msg_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pack2.pack2_msg.pack2_msg_msg",
  "Pack2MsgMsg",
  "Pack2__Pack2Msg__Pack2MsgMsg",
  "pack2",
  sizeof(Pack2__Pack2Msg__Pack2MsgMsg),
  3,
  pack2__pack2_msg__pack2_msg_msg__field_descriptors,
  pack2__pack2_msg__pack2_msg_msg__field_indices_by_name,
  1,  pack2__pack2_msg__pack2_msg_msg__number_ranges,
  (ProtobufCMessageInit) pack2__pack2_msg__pack2_msg_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue pack2__pack2_msg__pack2_msg_enum1__enum_values_by_number[2] =
{
  { "pack2_msg_enum1_value1", "PACK2__PACK2_MSG__PACK2_MSG_ENUM1__pack2_msg_enum1_value1", 0 },
  { "pack2_msg_enum1_value2", "PACK2__PACK2_MSG__PACK2_MSG_ENUM1__pack2_msg_enum1_value2", 1 },
};
static const ProtobufCIntRange pack2__pack2_msg__pack2_msg_enum1__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex pack2__pack2_msg__pack2_msg_enum1__enum_values_by_name[2] =
{
  { "pack2_msg_enum1_value1", 0 },
  { "pack2_msg_enum1_value2", 1 },
};
const ProtobufCEnumDescriptor pack2__pack2_msg__pack2_msg_enum1__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "pack2.pack2_msg.pack2_msg_enum1",
  "pack2_msg_enum1",
  "Pack2__Pack2Msg__Pack2MsgEnum1",
  "pack2",
  2,
  pack2__pack2_msg__pack2_msg_enum1__enum_values_by_number,
  2,
  pack2__pack2_msg__pack2_msg_enum1__enum_values_by_name,
  1,
  pack2__pack2_msg__pack2_msg_enum1__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue pack2__pack2_msg__pack2_msg_enum2__enum_values_by_number[2] =
{
  { "pack2_msg_enum2_value1", "PACK2__PACK2_MSG__PACK2_MSG_ENUM2__pack2_msg_enum2_value1", 0 },
  { "pack2_msg_enum2_value2", "PACK2__PACK2_MSG__PACK2_MSG_ENUM2__pack2_msg_enum2_value2", 2 },
};
static const ProtobufCIntRange pack2__pack2_msg__pack2_msg_enum2__value_ranges[] = {
{0, 0},{2, 1},{0, 2}
};
static const ProtobufCEnumValueIndex pack2__pack2_msg__pack2_msg_enum2__enum_values_by_name[2] =
{
  { "pack2_msg_enum2_value1", 0 },
  { "pack2_msg_enum2_value2", 1 },
};
const ProtobufCEnumDescriptor pack2__pack2_msg__pack2_msg_enum2__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "pack2.pack2_msg.pack2_msg_enum2",
  "pack2_msg_enum2",
  "Pack2__Pack2Msg__Pack2MsgEnum2",
  "pack2",
  2,
  pack2__pack2_msg__pack2_msg_enum2__enum_values_by_number,
  2,
  pack2__pack2_msg__pack2_msg_enum2__enum_values_by_name,
  2,
  pack2__pack2_msg__pack2_msg_enum2__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor pack2__pack2_msg__field_descriptors[4] =
{
  {
    "pack2_msg_value1",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Pack2__Pack2Msg, pack2_msg_value1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pack2_msg_value2",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(Pack2__Pack2Msg, pack2_msg_value2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pack2_msg_value3",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pack2__Pack2Msg, pack2_msg_value3),
    &pack2__pack2_msg__pack2_msg_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pack2_msg_value4",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Pack2__Pack2Msg, pack2_msg_value4),
    &pack2__pack2_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pack2__pack2_msg__field_indices_by_name[] = {
  0,   /* field[0] = pack2_msg_value1 */
  1,   /* field[1] = pack2_msg_value2 */
  2,   /* field[2] = pack2_msg_value3 */
  3,   /* field[3] = pack2_msg_value4 */
};
static const ProtobufCIntRange pack2__pack2_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor pack2__pack2_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pack2.pack2_msg",
  "Pack2Msg",
  "Pack2__Pack2Msg",
  "pack2",
  sizeof(Pack2__Pack2Msg),
  4,
  pack2__pack2_msg__field_descriptors,
  pack2__pack2_msg__field_indices_by_name,
  1,  pack2__pack2_msg__number_ranges,
  (ProtobufCMessageInit) pack2__pack2_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue pack2__pack2_enum__enum_values_by_number[2] =
{
  { "pack2_enum_value1", "PACK2__PACK2_ENUM__pack2_enum_value1", 0 },
  { "pack2_enum_value2", "PACK2__PACK2_ENUM__pack2_enum_value2", 2 },
};
static const ProtobufCIntRange pack2__pack2_enum__value_ranges[] = {
{0, 0},{2, 1},{0, 2}
};
static const ProtobufCEnumValueIndex pack2__pack2_enum__enum_values_by_name[2] =
{
  { "pack2_enum_value1", 0 },
  { "pack2_enum_value2", 1 },
};
const ProtobufCEnumDescriptor pack2__pack2_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "pack2.pack2_enum",
  "pack2_enum",
  "Pack2__Pack2Enum",
  "pack2",
  2,
  pack2__pack2_enum__enum_values_by_number,
  2,
  pack2__pack2_enum__enum_values_by_name,
  2,
  pack2__pack2_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
