/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pack2.proto */

#ifndef PROTOBUF_C_pack2_2eproto__INCLUDED
#define PROTOBUF_C_pack2_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Pack2__Pack2Msg Pack2__Pack2Msg;
typedef struct Pack2__Pack2Msg__Pack2MsgMsg Pack2__Pack2Msg__Pack2MsgMsg;


/* --- enums --- */

typedef enum _Pack2__Pack2Msg__Pack2MsgMsg__Pack2MsgMsgEnum {
  PACK2__PACK2_MSG__PACK2_MSG_MSG__PACK2_MSG_MSG_ENUM__pack2_msg_msg_enum_value1 = 0,
  PACK2__PACK2_MSG__PACK2_MSG_MSG__PACK2_MSG_MSG_ENUM__pack2_msg_msg_enum_value2 = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PACK2__PACK2_MSG__PACK2_MSG_MSG__PACK2_MSG_MSG_ENUM)
} Pack2__Pack2Msg__Pack2MsgMsg__Pack2MsgMsgEnum;
typedef enum _Pack2__Pack2Msg__Pack2MsgEnum1 {
  PACK2__PACK2_MSG__PACK2_MSG_ENUM1__pack2_msg_enum1_value1 = 0,
  PACK2__PACK2_MSG__PACK2_MSG_ENUM1__pack2_msg_enum1_value2 = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PACK2__PACK2_MSG__PACK2_MSG_ENUM1)
} Pack2__Pack2Msg__Pack2MsgEnum1;
typedef enum _Pack2__Pack2Msg__Pack2MsgEnum2 {
  PACK2__PACK2_MSG__PACK2_MSG_ENUM2__pack2_msg_enum2_value1 = 0,
  PACK2__PACK2_MSG__PACK2_MSG_ENUM2__pack2_msg_enum2_value2 = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PACK2__PACK2_MSG__PACK2_MSG_ENUM2)
} Pack2__Pack2Msg__Pack2MsgEnum2;
typedef enum _Pack2__Pack2Enum {
  PACK2__PACK2_ENUM__pack2_enum_value1 = 0,
  PACK2__PACK2_ENUM__pack2_enum_value2 = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PACK2__PACK2_ENUM)
} Pack2__Pack2Enum;

/* --- messages --- */

struct  Pack2__Pack2Msg__Pack2MsgMsg
{
  ProtobufCMessage base;
  Pack2__Pack2Msg__Pack2MsgEnum1 pack2_msg_msg_value1;
  Pack2__Pack2Msg__Pack2MsgEnum2 pack2_msg_msg_value2;
  Pack2__Pack2Msg__Pack2MsgMsg__Pack2MsgMsgEnum pack2_msg_msg_value3;
};
#define PACK2__PACK2_MSG__PACK2_MSG_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pack2__pack2_msg__pack2_msg_msg__descriptor) \
, PACK2__PACK2_MSG__PACK2_MSG_ENUM1__pack2_msg_enum1_value1, PACK2__PACK2_MSG__PACK2_MSG_ENUM2__pack2_msg_enum2_value1, PACK2__PACK2_MSG__PACK2_MSG_MSG__PACK2_MSG_MSG_ENUM__pack2_msg_msg_enum_value1 }


struct  Pack2__Pack2Msg
{
  ProtobufCMessage base;
  int64_t pack2_msg_value1;
  int64_t pack2_msg_value2;
  Pack2__Pack2Msg__Pack2MsgMsg *pack2_msg_value3;
  Pack2__Pack2Enum pack2_msg_value4;
};
#define PACK2__PACK2_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pack2__pack2_msg__descriptor) \
, 0, 0, NULL, PACK2__PACK2_ENUM__pack2_enum_value1 }


/* Pack2__Pack2Msg__Pack2MsgMsg methods */
void   pack2__pack2_msg__pack2_msg_msg__init
                     (Pack2__Pack2Msg__Pack2MsgMsg         *message);
/* Pack2__Pack2Msg methods */
void   pack2__pack2_msg__init
                     (Pack2__Pack2Msg         *message);
size_t pack2__pack2_msg__get_packed_size
                     (const Pack2__Pack2Msg   *message);
size_t pack2__pack2_msg__pack
                     (const Pack2__Pack2Msg   *message,
                      uint8_t             *out);
size_t pack2__pack2_msg__pack_to_buffer
                     (const Pack2__Pack2Msg   *message,
                      ProtobufCBuffer     *buffer);
Pack2__Pack2Msg *
       pack2__pack2_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pack2__pack2_msg__free_unpacked
                     (Pack2__Pack2Msg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Pack2__Pack2Msg__Pack2MsgMsg_Closure)
                 (const Pack2__Pack2Msg__Pack2MsgMsg *message,
                  void *closure_data);
typedef void (*Pack2__Pack2Msg_Closure)
                 (const Pack2__Pack2Msg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    pack2__pack2_enum__descriptor;
extern const ProtobufCMessageDescriptor pack2__pack2_msg__descriptor;
extern const ProtobufCMessageDescriptor pack2__pack2_msg__pack2_msg_msg__descriptor;
extern const ProtobufCEnumDescriptor    pack2__pack2_msg__pack2_msg_msg__pack2_msg_msg_enum__descriptor;
extern const ProtobufCEnumDescriptor    pack2__pack2_msg__pack2_msg_enum1__descriptor;
extern const ProtobufCEnumDescriptor    pack2__pack2_msg__pack2_msg_enum2__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_pack2_2eproto__INCLUDED */
