/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: demo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "demo.pb-c.h"
void   demo_pack__demo_msg__init
                     (DemoPack__DemoMsg         *message)
{
  static const DemoPack__DemoMsg init_value = DEMO_PACK__DEMO_MSG__INIT;
  *message = init_value;
}
size_t demo_pack__demo_msg__get_packed_size
                     (const DemoPack__DemoMsg *message)
{
  assert(message->base.descriptor == &demo_pack__demo_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t demo_pack__demo_msg__pack
                     (const DemoPack__DemoMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &demo_pack__demo_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t demo_pack__demo_msg__pack_to_buffer
                     (const DemoPack__DemoMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &demo_pack__demo_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DemoPack__DemoMsg *
       demo_pack__demo_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DemoPack__DemoMsg *)
     protobuf_c_message_unpack (&demo_pack__demo_msg__descriptor,
                                allocator, len, data);
}
void   demo_pack__demo_msg__free_unpacked
                     (DemoPack__DemoMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &demo_pack__demo_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor demo_pack__demo_msg__field_descriptors[2] =
{
  {
    "str",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DemoPack__DemoMsg, str),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DemoPack__DemoMsg, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned demo_pack__demo_msg__field_indices_by_name[] = {
  1,   /* field[1] = size */
  0,   /* field[0] = str */
};
static const ProtobufCIntRange demo_pack__demo_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor demo_pack__demo_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "demo_pack.demo_msg",
  "DemoMsg",
  "DemoPack__DemoMsg",
  "demo_pack",
  sizeof(DemoPack__DemoMsg),
  2,
  demo_pack__demo_msg__field_descriptors,
  demo_pack__demo_msg__field_indices_by_name,
  1,  demo_pack__demo_msg__number_ranges,
  (ProtobufCMessageInit) demo_pack__demo_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
