/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: demo.proto */

#ifndef PROTOBUF_C_demo_2eproto__INCLUDED
#define PROTOBUF_C_demo_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct DemoPack__DemoMsg DemoPack__DemoMsg;


/* --- enums --- */


/* --- messages --- */

struct  DemoPack__DemoMsg
{
  ProtobufCMessage base;
  ProtobufCBinaryData str;
  uint64_t size;
};
#define DEMO_PACK__DEMO_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&demo_pack__demo_msg__descriptor) \
, {0,NULL}, 0 }


/* DemoPack__DemoMsg methods */
void   demo_pack__demo_msg__init
                     (DemoPack__DemoMsg         *message);
size_t demo_pack__demo_msg__get_packed_size
                     (const DemoPack__DemoMsg   *message);
size_t demo_pack__demo_msg__pack
                     (const DemoPack__DemoMsg   *message,
                      uint8_t             *out);
size_t demo_pack__demo_msg__pack_to_buffer
                     (const DemoPack__DemoMsg   *message,
                      ProtobufCBuffer     *buffer);
DemoPack__DemoMsg *
       demo_pack__demo_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   demo_pack__demo_msg__free_unpacked
                     (DemoPack__DemoMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DemoPack__DemoMsg_Closure)
                 (const DemoPack__DemoMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor demo_pack__demo_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_demo_2eproto__INCLUDED */
