/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: default.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "default.pb-c.h"
void   packdef_msg__init
                     (PackdefMsg         *message)
{
  static const PackdefMsg init_value = PACKDEF_MSG__INIT;
  *message = init_value;
}
size_t packdef_msg__get_packed_size
                     (const PackdefMsg *message)
{
  assert(message->base.descriptor == &packdef_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t packdef_msg__pack
                     (const PackdefMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &packdef_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t packdef_msg__pack_to_buffer
                     (const PackdefMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &packdef_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PackdefMsg *
       packdef_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PackdefMsg *)
     protobuf_c_message_unpack (&packdef_msg__descriptor,
                                allocator, len, data);
}
void   packdef_msg__free_unpacked
                     (PackdefMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &packdef_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor packdef_msg__field_descriptors[3] =
{
  {
    "packdef_msg_value1",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PackdefMsg, packdef_msg_value1),
    &pack1__pack1_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packdef_msg_value2",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PackdefMsg, packdef_msg_value2),
    &pack2__pack2_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packdef_msg_enum",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(PackdefMsg, has_packdef_msg_enum),
    offsetof(PackdefMsg, packdef_msg_enum),
    &packdef_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned packdef_msg__field_indices_by_name[] = {
  2,   /* field[2] = packdef_msg_enum */
  0,   /* field[0] = packdef_msg_value1 */
  1,   /* field[1] = packdef_msg_value2 */
};
static const ProtobufCIntRange packdef_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor packdef_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "packdef_msg",
  "PackdefMsg",
  "PackdefMsg",
  "",
  sizeof(PackdefMsg),
  3,
  packdef_msg__field_descriptors,
  packdef_msg__field_indices_by_name,
  1,  packdef_msg__number_ranges,
  (ProtobufCMessageInit) packdef_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue packdef_enum__enum_values_by_number[2] =
{
  { "packdef_enum_value1", "PACKDEF_ENUM__packdef_enum_value1", 1 },
  { "packdef_enum_value2", "PACKDEF_ENUM__packdef_enum_value2", 2 },
};
static const ProtobufCIntRange packdef_enum__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex packdef_enum__enum_values_by_name[2] =
{
  { "packdef_enum_value1", 0 },
  { "packdef_enum_value2", 1 },
};
const ProtobufCEnumDescriptor packdef_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "packdef_enum",
  "packdef_enum",
  "PackdefEnum",
  "",
  2,
  packdef_enum__enum_values_by_number,
  2,
  packdef_enum__enum_values_by_name,
  1,
  packdef_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
