/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: default.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "default.pb-c.h"
void   packdef_msg__init
                     (PackdefMsg         *message)
{
  static const PackdefMsg init_value = PACKDEF_MSG__INIT;
  *message = init_value;
}
size_t packdef_msg__get_packed_size
                     (const PackdefMsg *message)
{
  assert(message->base.descriptor == &packdef_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t packdef_msg__pack
                     (const PackdefMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &packdef_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t packdef_msg__pack_to_buffer
                     (const PackdefMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &packdef_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PackdefMsg *
       packdef_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PackdefMsg *)
     protobuf_c_message_unpack (&packdef_msg__descriptor,
                                allocator, len, data);
}
void   packdef_msg__free_unpacked
                     (PackdefMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &packdef_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor packdef_msg__field_descriptors[18] =
{
  {
    "value1",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(PackdefMsg, has_value1),
    offsetof(PackdefMsg, value1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value2",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(PackdefMsg, has_value2),
    offsetof(PackdefMsg, value2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value3",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(PackdefMsg, has_value3),
    offsetof(PackdefMsg, value3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value4",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(PackdefMsg, has_value4),
    offsetof(PackdefMsg, value4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value5",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(PackdefMsg, has_value5),
    offsetof(PackdefMsg, value5),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value6",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(PackdefMsg, has_value6),
    offsetof(PackdefMsg, value6),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value7",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(PackdefMsg, has_value7),
    offsetof(PackdefMsg, value7),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value8",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(PackdefMsg, has_value8),
    offsetof(PackdefMsg, value8),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value9",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(PackdefMsg, has_value9),
    offsetof(PackdefMsg, value9),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value10",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(PackdefMsg, has_value10),
    offsetof(PackdefMsg, value10),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value11",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SFIXED32,
    offsetof(PackdefMsg, has_value11),
    offsetof(PackdefMsg, value11),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value12",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SFIXED64,
    offsetof(PackdefMsg, has_value12),
    offsetof(PackdefMsg, value12),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value13",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(PackdefMsg, has_value13),
    offsetof(PackdefMsg, value13),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value14",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PackdefMsg, value14),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value15",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(PackdefMsg, has_value15),
    offsetof(PackdefMsg, value15),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packdef_msg_value1",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PackdefMsg, packdef_msg_value1),
    &pack1__pack1_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packdef_msg_value2",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(PackdefMsg, packdef_msg_value2),
    &pack2__pack2_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "packdef_msg_enum",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(PackdefMsg, has_packdef_msg_enum),
    offsetof(PackdefMsg, packdef_msg_enum),
    &packdef_enum__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned packdef_msg__field_indices_by_name[] = {
  17,   /* field[17] = packdef_msg_enum */
  15,   /* field[15] = packdef_msg_value1 */
  16,   /* field[16] = packdef_msg_value2 */
  0,   /* field[0] = value1 */
  9,   /* field[9] = value10 */
  10,   /* field[10] = value11 */
  11,   /* field[11] = value12 */
  12,   /* field[12] = value13 */
  13,   /* field[13] = value14 */
  14,   /* field[14] = value15 */
  1,   /* field[1] = value2 */
  2,   /* field[2] = value3 */
  3,   /* field[3] = value4 */
  4,   /* field[4] = value5 */
  5,   /* field[5] = value6 */
  6,   /* field[6] = value7 */
  7,   /* field[7] = value8 */
  8,   /* field[8] = value9 */
};
static const ProtobufCIntRange packdef_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 18 }
};
const ProtobufCMessageDescriptor packdef_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "packdef_msg",
  "PackdefMsg",
  "PackdefMsg",
  "",
  sizeof(PackdefMsg),
  18,
  packdef_msg__field_descriptors,
  packdef_msg__field_indices_by_name,
  1,  packdef_msg__number_ranges,
  (ProtobufCMessageInit) packdef_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue packdef_enum__enum_values_by_number[2] =
{
  { "packdef_enum_value1", "PACKDEF_ENUM__packdef_enum_value1", 1 },
  { "packdef_enum_value2", "PACKDEF_ENUM__packdef_enum_value2", 2 },
};
static const ProtobufCIntRange packdef_enum__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex packdef_enum__enum_values_by_name[2] =
{
  { "packdef_enum_value1", 0 },
  { "packdef_enum_value2", 1 },
};
const ProtobufCEnumDescriptor packdef_enum__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "packdef_enum",
  "packdef_enum",
  "PackdefEnum",
  "",
  2,
  packdef_enum__enum_values_by_number,
  2,
  packdef_enum__enum_values_by_name,
  1,
  packdef_enum__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
