/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: default.proto */

#ifndef PROTOBUF_C_default_2eproto__INCLUDED
#define PROTOBUF_C_default_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "pack1.pb-c.h"
#include "pack2.pb-c.h"

typedef struct PackdefMsg PackdefMsg;


/* --- enums --- */

typedef enum _PackdefEnum {
  PACKDEF_ENUM__packdef_enum_value1 = 1,
  PACKDEF_ENUM__packdef_enum_value2 = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(PACKDEF_ENUM)
} PackdefEnum;

/* --- messages --- */

struct  PackdefMsg
{
  ProtobufCMessage base;
  protobuf_c_boolean has_value1;
  double value1;
  protobuf_c_boolean has_value2;
  float value2;
  protobuf_c_boolean has_value3;
  int32_t value3;
  protobuf_c_boolean has_value4;
  int64_t value4;
  protobuf_c_boolean has_value5;
  uint32_t value5;
  protobuf_c_boolean has_value6;
  uint64_t value6;
  protobuf_c_boolean has_value7;
  int32_t value7;
  protobuf_c_boolean has_value8;
  int64_t value8;
  protobuf_c_boolean has_value9;
  uint32_t value9;
  protobuf_c_boolean has_value10;
  uint64_t value10;
  protobuf_c_boolean has_value11;
  int32_t value11;
  protobuf_c_boolean has_value12;
  int64_t value12;
  protobuf_c_boolean has_value13;
  protobuf_c_boolean value13;
  char *value14;
  protobuf_c_boolean has_value15;
  ProtobufCBinaryData value15;
  Pack1__Pack1Msg *packdef_msg_value1;
  Pack2__Pack2Msg *packdef_msg_value2;
  protobuf_c_boolean has_packdef_msg_enum;
  PackdefEnum packdef_msg_enum;
};
#define PACKDEF_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&packdef_msg__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, {0,NULL}, NULL, NULL, 0, PACKDEF_ENUM__packdef_enum_value1 }


/* PackdefMsg methods */
void   packdef_msg__init
                     (PackdefMsg         *message);
size_t packdef_msg__get_packed_size
                     (const PackdefMsg   *message);
size_t packdef_msg__pack
                     (const PackdefMsg   *message,
                      uint8_t             *out);
size_t packdef_msg__pack_to_buffer
                     (const PackdefMsg   *message,
                      ProtobufCBuffer     *buffer);
PackdefMsg *
       packdef_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   packdef_msg__free_unpacked
                     (PackdefMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PackdefMsg_Closure)
                 (const PackdefMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    packdef_enum__descriptor;
extern const ProtobufCMessageDescriptor packdef_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_default_2eproto__INCLUDED */
