/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pack1.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pack1.pb-c.h"
void   pack1__pack1_msg__init
                     (Pack1__Pack1Msg         *message)
{
  static const Pack1__Pack1Msg init_value = PACK1__PACK1_MSG__INIT;
  *message = init_value;
}
size_t pack1__pack1_msg__get_packed_size
                     (const Pack1__Pack1Msg *message)
{
  assert(message->base.descriptor == &pack1__pack1_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pack1__pack1_msg__pack
                     (const Pack1__Pack1Msg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pack1__pack1_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pack1__pack1_msg__pack_to_buffer
                     (const Pack1__Pack1Msg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pack1__pack1_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pack1__Pack1Msg *
       pack1__pack1_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pack1__Pack1Msg *)
     protobuf_c_message_unpack (&pack1__pack1_msg__descriptor,
                                allocator, len, data);
}
void   pack1__pack1_msg__free_unpacked
                     (Pack1__Pack1Msg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pack1__pack1_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pack1__pack2_msg__init
                     (Pack1__Pack2Msg         *message)
{
  static const Pack1__Pack2Msg init_value = PACK1__PACK2_MSG__INIT;
  *message = init_value;
}
size_t pack1__pack2_msg__get_packed_size
                     (const Pack1__Pack2Msg *message)
{
  assert(message->base.descriptor == &pack1__pack2_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pack1__pack2_msg__pack
                     (const Pack1__Pack2Msg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pack1__pack2_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pack1__pack2_msg__pack_to_buffer
                     (const Pack1__Pack2Msg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pack1__pack2_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pack1__Pack2Msg *
       pack1__pack2_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pack1__Pack2Msg *)
     protobuf_c_message_unpack (&pack1__pack2_msg__descriptor,
                                allocator, len, data);
}
void   pack1__pack2_msg__free_unpacked
                     (Pack1__Pack2Msg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pack1__pack2_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pack1__pack3_msg__init
                     (Pack1__Pack3Msg         *message)
{
  static const Pack1__Pack3Msg init_value = PACK1__PACK3_MSG__INIT;
  *message = init_value;
}
size_t pack1__pack3_msg__get_packed_size
                     (const Pack1__Pack3Msg *message)
{
  assert(message->base.descriptor == &pack1__pack3_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pack1__pack3_msg__pack
                     (const Pack1__Pack3Msg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pack1__pack3_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pack1__pack3_msg__pack_to_buffer
                     (const Pack1__Pack3Msg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pack1__pack3_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pack1__Pack3Msg *
       pack1__pack3_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pack1__Pack3Msg *)
     protobuf_c_message_unpack (&pack1__pack3_msg__descriptor,
                                allocator, len, data);
}
void   pack1__pack3_msg__free_unpacked
                     (Pack1__Pack3Msg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pack1__pack3_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pack1__pack1_msg__field_descriptors[2] =
{
  {
    "pack1_msg_value1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Pack1__Pack1Msg, pack1_msg_value1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pack1_msg_value2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(Pack1__Pack1Msg, pack1_msg_value2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pack1__pack1_msg__field_indices_by_name[] = {
  0,   /* field[0] = pack1_msg_value1 */
  1,   /* field[1] = pack1_msg_value2 */
};
static const ProtobufCIntRange pack1__pack1_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pack1__pack1_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pack1.pack1_msg",
  "Pack1Msg",
  "Pack1__Pack1Msg",
  "pack1",
  sizeof(Pack1__Pack1Msg),
  2,
  pack1__pack1_msg__field_descriptors,
  pack1__pack1_msg__field_indices_by_name,
  1,  pack1__pack1_msg__number_ranges,
  (ProtobufCMessageInit) pack1__pack1_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pack1__pack2_msg__field_descriptors[2] =
{
  {
    "pack1_pack2_msg_value1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Pack1__Pack2Msg, pack1_pack2_msg_value1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pack1_pack2_msg_value2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(Pack1__Pack2Msg, pack1_pack2_msg_value2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pack1__pack2_msg__field_indices_by_name[] = {
  0,   /* field[0] = pack1_pack2_msg_value1 */
  1,   /* field[1] = pack1_pack2_msg_value2 */
};
static const ProtobufCIntRange pack1__pack2_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pack1__pack2_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pack1.pack2_msg",
  "Pack2Msg",
  "Pack1__Pack2Msg",
  "pack1",
  sizeof(Pack1__Pack2Msg),
  2,
  pack1__pack2_msg__field_descriptors,
  pack1__pack2_msg__field_indices_by_name,
  1,  pack1__pack2_msg__number_ranges,
  (ProtobufCMessageInit) pack1__pack2_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pack1__pack3_msg__field_descriptors[2] =
{
  {
    "pack2_msg_value1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pack1__Pack3Msg, pack2_msg_value1),
    &pack1__pack2_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pack2_msg_value2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pack1__Pack3Msg, pack2_msg_value2),
    &pack2__pack2_msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pack1__pack3_msg__field_indices_by_name[] = {
  0,   /* field[0] = pack2_msg_value1 */
  1,   /* field[1] = pack2_msg_value2 */
};
static const ProtobufCIntRange pack1__pack3_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pack1__pack3_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pack1.pack3_msg",
  "Pack3Msg",
  "Pack1__Pack3Msg",
  "pack1",
  sizeof(Pack1__Pack3Msg),
  2,
  pack1__pack3_msg__field_descriptors,
  pack1__pack3_msg__field_indices_by_name,
  1,  pack1__pack3_msg__number_ranges,
  (ProtobufCMessageInit) pack1__pack3_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
